# Generated by Django 5.2 on 2026-08-18 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='home_products_cta_label',
            field=models.CharField(blank=True, default='See all products', help_text='Links to the products page. Leave blank to hide the button.', max_length=60, verbose_name='Button under the grid'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_products_eyebrow',
            field=models.CharField(default='Featured setups', help_text='The small line above the heading of the homepage products block.', max_length=60, verbose_name='Homepage eyebrow'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_products_lead',
            field=models.CharField(blank=True, default='Every price below is final: materials, labour, travel inside city limits and clean-up.', max_length=240, verbose_name='Homepage sub-heading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_products_limit',
            field=models.PositiveIntegerField(default=8, help_text='The homepage shows this many products; the rest live on the products page.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='How many to show at home'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_products_source',
            field=models.CharField(choices=[('featured', 'Featured first'), ('newest', 'Newest first'), ('rating', 'Highest rated'), ('discount', 'Biggest discount'), ('popular', 'Most reviewed'), ('manual', 'The order you dragged them into')], default='featured', max_length=20, verbose_name='Which ones to show'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_products_title',
            field=models.CharField(default='Booked most this month', max_length=120, verbose_name='Homepage heading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_page_eyebrow',
            field=models.CharField(default='The full catalogue', max_length=60, verbose_name='Products page eyebrow'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_page_lead',
            field=models.CharField(blank=True, default='Filter by occasion, budget and rating. Every price is final and includes delivery, setup and clean-up.', max_length=240, verbose_name='Products page sub-heading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_page_title',
            field=models.CharField(default='Every setup we build', max_length=120, verbose_name='Products page heading'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_per_page',
            field=models.PositiveIntegerField(default=9, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(48)], verbose_name='Products per page'),
        ),
    ]
