# Generated by Django 5.2 on 2026-08-20 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_products_nav_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_file',
            field=models.FileField(blank=True, help_text='PNG, WebP or SVG with a transparent background works best.', upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif', 'svg'])], verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_fit',
            field=models.CharField(choices=[('contain', 'Fit inside the box, no cropping'), ('cover', 'Fill the box, cropping the edges')], default='contain', max_length=10, verbose_name='How the logo fits its box'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_focal',
            field=models.CharField(default='50% 50%', help_text="Which part of the image stays visible when it's cropped, e.g. '50% 50%' for centred or '50% 20%' to favour the top. Only used when filling & cropping.", max_length=20, verbose_name='Logo crop position'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='…or a logo URL'),
        ),
    ]
