# Generated by Django 5.2 on 2026-08-20 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_logo_file_sitesettings_logo_fit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_height',
            field=models.PositiveIntegerField(default=48, help_text='How tall the logo sits in the header. Paired with the width to control exact logo dimensions.', validators=[django.core.validators.MinValueValidator(24), django.core.validators.MaxValueValidator(320)], verbose_name='Logo box height (px)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_show_name',
            field=models.BooleanField(default=True, help_text='Turn off if the logo image already contains the brand name, so the text does not repeat.', verbose_name='Show site name next to logo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_width',
            field=models.PositiveIntegerField(default=48, help_text='How wide the logo sits in the header. The height is fixed, so this is what shapes the box: leave it near 48 for a square mark, or raise it to 150–220 for a wide logo that includes the name. When filling & cropping, a wider box crops away the empty space above and below the artwork.', validators=[django.core.validators.MinValueValidator(24), django.core.validators.MaxValueValidator(320)], verbose_name='Logo box width (px)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='hello@barahiflorist.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_focal',
            field=models.CharField(default='50% 50%', help_text="Which part of the image stays visible when it's cropped, e.g. '50% 50%' for centred or '20% 50%' to favour the left. Only used when filling & cropping.", max_length=20, verbose_name='Logo crop position'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(default='Barahi Florist & Events', max_length=80),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='Florist and Event Decorators', max_length=160),
        ),
    ]
