# Generated by Django 5.2 on 2026-09-09 07:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_staff_types_and_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_file', models.FileField(blank=True, help_text='JPG, PNG, WebP, AVIF, GIF or SVG.', upload_to='uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif', 'svg'])], verbose_name='Upload an image')),
                ('image_url', models.URLField(blank=True, help_text='Used only when nothing is uploaded.', max_length=500, verbose_name='…or paste an image URL')),
                ('sku', models.CharField(blank=True, help_text='Left blank, one is made from the name.', max_length=32, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('pack', 'Pack'), ('box', 'Box'), ('set', 'Set'), ('pair', 'Pair'), ('roll', 'Roll'), ('metre', 'Metre'), ('kg', 'Kilogram'), ('litre', 'Litre'), ('hour', 'Hour')], default='piece', help_text='What one of these is.', max_length=10, verbose_name='Counted in')),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='Optional. The counter search looks at this too, so a scanner works.', max_length=40)),
                ('location', models.CharField(blank=True, help_text='Where to find it — rack, shelf, room.', max_length=60, verbose_name='Shelf')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Kept in step by the stock ledger. Use an adjustment to change it.', max_digits=12, verbose_name='In stock')),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, help_text='Drop to this and the item is flagged as running low. 0 turns the warning off.', max_digits=12, verbose_name='Reorder at')),
                ('cost_price', models.PositiveIntegerField(default=0, help_text='What one costs you (₹).')),
                ('sale_price', models.PositiveIntegerField(default=0, help_text='What one sells for at the counter (₹).')),
                ('is_sellable', models.BooleanField(default=True, help_text='Off for consumables you track but never sell over the counter.', verbose_name='Sell at the counter')),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to retire an item without losing its history.', verbose_name='Active')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Stock item',
                'verbose_name_plural': 'Stock items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Drag rows in the list to reorder.')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('description', models.CharField(blank=True, help_text='What belongs in this group.', max_length=200)),
                ('tone', models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('violet', 'Violet'), ('amber', 'Amber'), ('red', 'Red'), ('grey', 'Grey')], default='grey', help_text='The colour this group wears wherever it is shown.', max_length=10, verbose_name='Badge colour')),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to retire a group. Existing items keep it.', verbose_name='Selectable')),
            ],
            options={
                'verbose_name': 'Stock group',
                'verbose_name_plural': 'Stock groups',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=80, verbose_name='Contact person')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, verbose_name='GSTIN')),
                ('lead_time_days', models.PositiveSmallIntegerField(default=0, help_text='How long an order usually takes to arrive. 0 if it is bought over the counter.', verbose_name='Lead time (days)')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to retire a supplier. Existing stock keeps them.', verbose_name='Selectable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CounterSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(blank=True, help_text='Optional — a walk-in needs no name.', max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('sold_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Sold')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank', 'Bank transfer'), ('credit', 'On account')], default='cash', max_length=10, verbose_name='Paid by')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('refunded', 'Refunded')], db_index=True, default='completed', max_length=10)),
                ('subtotal', models.PositiveIntegerField(default=0, editable=False)),
                ('discount', models.PositiveIntegerField(default=0, help_text='Flat ₹ off the whole sale.')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, help_text='GST or similar, applied after the discount. 0 for none.', max_digits=5, verbose_name='Tax %')),
                ('tax_amount', models.PositiveIntegerField(default=0, editable=False)),
                ('total', models.PositiveIntegerField(default=0, editable=False)),
                ('amount_tendered', models.PositiveIntegerField(default=0, help_text='What the customer handed over, for the change line on the receipt.', verbose_name='Cash taken')),
                ('cost_total', models.PositiveIntegerField(default=0, editable=False)),
                ('notes', models.TextField(blank=True)),
                ('stock_applied', models.BooleanField(default=False, editable=False)),
                ('cashier', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_sales', to=settings.AUTH_USER_MODEL)),
                ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_sales', to='core.staffmember', verbose_name='Sold by')),
            ],
            options={
                'verbose_name': 'Counter sale',
                'verbose_name_plural': 'Counter sales',
                'ordering': ['-sold_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CounterSaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sku', models.CharField(blank=True, max_length=32)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.PositiveIntegerField(default=0)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.countersale')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='core.inventoryitem')),
            ],
            options={
                'verbose_name': 'Sale line',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Where this lives. The list is managed under Stock groups.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.stockcategory', verbose_name='Stock group'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('opening', 'Opening balance'), ('purchase', 'Purchase in'), ('sale', 'Counter sale'), ('return_in', 'Customer return'), ('return_out', 'Returned to supplier'), ('event', 'Used on a booking'), ('damage', 'Damaged or lost'), ('adjustment', 'Stock count adjustment')], db_index=True, default='purchase', max_length=12, verbose_name='Reason')),
                ('change', models.DecimalField(decimal_places=2, help_text='How many units moved. A negative number takes stock out.', max_digits=12, verbose_name='Quantity')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Stock after')),
                ('unit_cost', models.PositiveIntegerField(default=0, help_text='What one unit cost on this movement (₹). Purchases mostly.')),
                ('reference', models.CharField(blank=True, help_text='Invoice or delivery-note number.', max_length=40)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(blank=True, help_text='If this stock went out on a job, which one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.booking')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.inventoryitem')),
                ('sale', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='core.countersale')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='core.supplier')),
            ],
            options={
                'verbose_name': 'Stock movement',
                'verbose_name_plural': 'Stock ledger',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Who this is normally bought from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.supplier'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['is_active', 'quantity'], name='core_invent_is_acti_cad1d3_idx'),
        ),
    ]
