# Generated by Django 5.2 on 2026-09-13 09:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_inventoryitem_stockcategory_supplier_countersale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='usage_type',
            field=models.CharField(choices=[('consumable', 'Consumable — used up (water, plates, flowers)'), ('reusable', 'Reusable — comes back (chairs, speakers, lights)')], db_index=True, default='consumable', help_text='Reusable stock is only reserved for an event and comes back afterwards. Consumable stock is used up and leaves the shelf.', max_length=12, verbose_name='Kind of stock'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='held_change',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Units put on hold for an event (+) or let go again (−). A hold never changes the shelf count, only what is free to use.', max_digits=12, verbose_name='Reserved change'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('opening', 'Opening balance'), ('purchase', 'Purchase in'), ('sale', 'Counter sale'), ('return_in', 'Customer return'), ('return_out', 'Returned to supplier'), ('event', 'Used on a booking or event'), ('damage', 'Damaged'), ('lost', 'Lost'), ('adjustment', 'Stock count adjustment'), ('reserve', 'Reserved for an event'), ('event_return', 'Back from an event'), ('release', 'Reservation released')], db_index=True, default='purchase', max_length=12, verbose_name='Reason'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Event number')),
                ('name', models.CharField(max_length=160, verbose_name='Event name')),
                ('event_date', models.DateField(db_index=True, verbose_name='Event date')),
                ('location', models.CharField(blank=True, help_text='Venue and address — where the crew goes.', max_length=200)),
                ('guests', models.PositiveIntegerField(default=0, verbose_name='Number of guests')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=12)),
                ('revenue', models.PositiveIntegerField(default=0, help_text='What the customer pays for the whole event (₹).', verbose_name='Revenue')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.customer')),
            ],
            options={
                'ordering': ['-event_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='event',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.event'),
        ),
        migrations.CreateModel(
            name='EventExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Expense')),
                ('category', models.CharField(choices=[('transport', 'Transportation'), ('venue', 'Venue'), ('staff', 'Staff'), ('decoration', 'Decoration'), ('food', 'Food'), ('fuel', 'Fuel'), ('other', 'Other')], default='other', max_length=12)),
                ('amount', models.PositiveIntegerField(help_text='In ₹.', validators=[django.core.validators.MinValueValidator(1)])),
                ('spent_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_expenses', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.event')),
            ],
            options={
                'verbose_name': 'Event expense',
                'ordering': ['-spent_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EventItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('inventory', 'Inventory item'), ('external', 'External item')], db_index=True, default='inventory', max_length=10)),
                ('name', models.CharField(max_length=120, verbose_name='Item name')),
                ('usage_type', models.CharField(blank=True, choices=[('consumable', 'Consumable — used up (water, plates, flowers)'), ('reusable', 'Reusable — comes back (chairs, speakers, lights)')], editable=False, max_length=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_cost', models.PositiveIntegerField(default=0, help_text='What one costs (₹).', verbose_name='Unit cost')),
                ('vendor', models.CharField(blank=True, help_text='For a one-off vendor who is not in your supplier list.', max_length=120, verbose_name='…or vendor name')),
                ('notes', models.TextField(blank=True)),
                ('reserved_qty', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('returned_qty', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('consumed_qty', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('damaged_qty', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('lost_qty', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.event')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_lines', to='core.inventoryitem', verbose_name='Stock item')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_items', to='core.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Event item',
                'ordering': ['item_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('amount', models.PositiveIntegerField(help_text='In ₹.', validators=[django.core.validators.MinValueValidator(1)])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank transfer'), ('card', 'Card'), ('cheque', 'Cheque')], default='cash', max_length=10, verbose_name='Paid by')),
                ('reference', models.CharField(blank=True, help_text='UTR, cheque number or receipt number.', max_length=60)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.event')),
                ('received_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event payment',
                'ordering': ['-paid_on', '-id'],
            },
        ),
    ]
