# Generated by Django 5.2 on 2026-09-13 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_events_customers_and_stock_holds'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventitem',
            name='image_file',
            field=models.FileField(blank=True, help_text='JPG, PNG, WebP, AVIF, GIF or SVG.', upload_to='uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'avif', 'gif', 'svg'])], verbose_name='Upload an image'),
        ),
        migrations.AddField(
            model_name='eventitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='Used only when nothing is uploaded.', max_length=500, verbose_name='…or paste an image URL'),
        ),
    ]
