# Generated by Django 5.2 on 2026-09-13 11:46

from django.db import migrations, models

# What the panel's activity log wrote for each step, and the stamp it fills.
LOGGED = {
    "confirmed": "confirmed_at",
    "started": "started_at",
    "completed": "completed_at",
    "cancelled": "cancelled_at",
}


def stamp_from_activity(apps, schema_editor):
    """Events changed before stamps existed get theirs from the activity log."""
    Event = apps.get_model("core", "Event")
    ActivityLog = apps.get_model("core", "ActivityLog")
    for event in Event.objects.exclude(status="draft").exclude(number=None):
        changed = []
        entries = ActivityLog.objects.filter(
            model_label="Event",
            object_label__startswith=f"{event.number} ·",
            detail__in=list(LOGGED),
        ).order_by("created_at")
        for entry in entries:
            field = LOGGED[entry.detail]
            if getattr(event, field) is None:
                setattr(event, field, entry.created_at)
                changed.append(field)
        if changed:
            event.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_event_item_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(stamp_from_activity, migrations.RunPython.noop),
    ]
