# Generated by Django 5.2 on 2026-09-14 04:43

import django.db.models.deletion
from django.db import migrations, models


def call_them_occasions(apps, schema_editor):
    """
    The site said "Categories" in the menu and "occasions" on the page behind
    it. One word now, and events already named after an occasion get linked.
    """
    NavLink = apps.get_model("core", "NavLink")
    NavLink.objects.filter(url_name="core:categories", label__iexact="Categories").update(
        label="Occasions"
    )

    Category = apps.get_model("core", "Category")
    Event = apps.get_model("core", "Event")
    occasions = list(Category.objects.all())
    for event in Event.objects.filter(occasion__isnull=True):
        name = event.name.lower()
        match = next((o for o in occasions if o.name.lower() in name), None)
        if match:
            event.occasion = match
            event.save(update_fields=["occasion"])


def call_them_categories(apps, schema_editor):
    NavLink = apps.get_model("core", "NavLink")
    NavLink.objects.filter(url_name="core:categories", label="Occasions").update(
        label="Categories"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_status_stamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Occasion', 'verbose_name_plural': 'Occasions'},
        ),
        migrations.AddField(
            model_name='enquiry',
            name='event',
            field=models.ForeignKey(blank=True, editable=False, help_text='The event this enquiry turned into.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='core.event'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='guests',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of guests'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='core.package', verbose_name='About the setup'),
        ),
        migrations.AddField(
            model_name='event',
            name='booked_extras',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_new',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='occasion',
            field=models.ForeignKey(blank=True, help_text='What is being celebrated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.category'),
        ),
        migrations.AddField(
            model_name='event',
            name='package',
            field=models.ForeignKey(blank=True, help_text='The setup from the website this event is built around, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.package', verbose_name='Setup'),
        ),
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('panel', 'Added in the panel'), ('website', 'Booked on the website'), ('enquiry', 'From an enquiry')], db_index=True, default='panel', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='time_slot',
            field=models.CharField(blank=True, help_text='When the crew is expected, e.g. 4 PM – 6 PM.', max_length=40, verbose_name='Arrival window'),
        ),
        migrations.RunPython(call_them_occasions, call_them_categories),
    ]
