# Generated by Django 5.2 on 2026-09-14 05:21

from django.db import migrations, models


def keep_ledger_references(apps, schema_editor):
    """
    The old Booking table goes; events replace it. Ledger rows that pointed at
    a booking keep its reference (CEL-1042) as text, so history still reads.
    """
    StockMovement = apps.get_model("core", "StockMovement")
    for move in StockMovement.objects.filter(booking__isnull=False).select_related("booking"):
        if not move.reference:
            move.reference = move.booking.reference[:40]
            move.save(update_fields=["reference"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_website_bookings'),
    ]

    operations = [
        migrations.RunPython(keep_ledger_references, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='stockmovement',
            name='booking',
        ),
        migrations.AddField(
            model_name='event',
            name='crew',
            field=models.ManyToManyField(blank=True, help_text='Who works this event — decorators, florists, drivers.', related_name='events', to='core.staffmember'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma separated — balloons, mandap, drone. Shown when you put them on an event.', max_length=160),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='kind',
            field=models.CharField(choices=[('opening', 'Opening balance'), ('purchase', 'Purchase in'), ('sale', 'Counter sale'), ('return_in', 'Customer return'), ('return_out', 'Returned to supplier'), ('event', 'Used on an event'), ('damage', 'Damaged'), ('lost', 'Lost'), ('adjustment', 'Stock count adjustment'), ('reserve', 'Reserved for an event'), ('event_return', 'Back from an event'), ('release', 'Reservation released')], db_index=True, default='purchase', max_length=12, verbose_name='Reason'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner — everything, including staff accounts'), ('admin', 'Admin — everything except staff accounts'), ('editor', 'Editor — content and events, no settings'), ('viewer', 'Viewer — read only')], default='editor', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner — everything, including staff accounts'), ('admin', 'Admin — everything except staff accounts'), ('editor', 'Editor — content and events, no settings'), ('viewer', 'Viewer — read only')], default='editor', max_length=10),
        ),
    ]
