# Generated by Django 5.2 on 2026-09-14 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_retire_old_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countersale',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Flat Rs. off the whole sale.'),
        ),
        migrations.AlterField(
            model_name='countersale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'eSewa / Khalti'), ('card', 'Card'), ('bank', 'Bank transfer'), ('credit', 'On account')], default='cash', max_length=10, verbose_name='Paid by'),
        ),
        migrations.AlterField(
            model_name='countersale',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT or similar, applied after the discount. 0 for none.', max_digits=5, verbose_name='Tax %'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='kind',
            field=models.CharField(choices=[('percent', 'Percent off'), ('flat', 'Flat Rs. off')], default='percent', max_length=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.PositiveIntegerField(help_text='15 means 15% or Rs. 15 depending on the kind.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='revenue',
            field=models.PositiveIntegerField(default=0, help_text='What the customer pays for the whole event (Rs.).', verbose_name='Revenue'),
        ),
        migrations.AlterField(
            model_name='eventexpense',
            name='amount',
            field=models.PositiveIntegerField(help_text='In Rs.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='eventitem',
            name='unit_cost',
            field=models.PositiveIntegerField(default=0, help_text='What one costs (Rs.).', verbose_name='Unit cost'),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='amount',
            field=models.PositiveIntegerField(help_text='In Rs.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'eSewa / Khalti'), ('bank', 'Bank transfer'), ('card', 'Card'), ('cheque', 'Cheque')], default='cash', max_length=10, verbose_name='Paid by'),
        ),
        migrations.AlterField(
            model_name='eventpayment',
            name='reference',
            field=models.CharField(blank=True, help_text='Transaction ID, cheque number or receipt number.', max_length=60),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='cost_price',
            field=models.PositiveIntegerField(default=0, help_text='What one costs you (Rs.).'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='sale_price',
            field=models.PositiveIntegerField(default=0, help_text='What one sells for at the counter (Rs.).'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.PositiveIntegerField(help_text='What the customer pays (Rs.).'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_city',
            field=models.CharField(default='Kathmandu', max_length=80),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='free_delivery_threshold',
            field=models.PositiveIntegerField(default=3000, help_text='Cart subtotal above which delivery is free (Rs.).'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+977 985-1234567', max_length=40),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=13, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, default='+977 985-1234567', max_length=40),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.PositiveIntegerField(default=0, help_text='What one unit cost on this movement (Rs.). Purchases mostly.'),
        ),
    ]
