# Generated by Django 5.2 on 2026-09-14 11:33
"""
One word for the thing customers book: "product". "Setup" stays only where it
means the act of setting up ("delivery, setup and clean-up", "Setup time").

The data step rewrites seeded copy only where a row still holds the exact
original text, so anything someone has edited in the panel is left alone.
"""

import django.db.models.deletion
from django.db import migrations, models

# (model, field): [(old, new), ...]
SEEDED_COPY = {
    ("SiteSettings", "home_products_eyebrow"): [("Featured setups", "Featured products")],
    ("SiteSettings", "products_page_title"): [("Every setup we build", "Every product we offer")],
    ("HeroSlide", "cta_label"): [("Browse birthday setups", "Browse birthday products")],
    ("TrustBadge", "label"): [("Setups every month", "Events every month")],
    ("Category", "blurb"): [
        ("Warm, grown-up setups built around the two of you.",
         "Warm, grown-up decorations built around the two of you."),
    ],
    ("FAQ", "question"): [("Will the setup look like the photos?", "Will the decoration look like the photos?")],
    ("FAQ", "answer"): [
        ("Three days is comfortable and gets you the widest choice of slots. Same-day booking is "
         "available in every metro if you order before 2 PM, and a handful of compact setups go out "
         "in ninety minutes.",
         "Three days is comfortable and gets you the widest choice of slots. Same-day booking is "
         "available in every metro if you order before 2 PM, and a handful of compact products go out "
         "in ninety minutes."),
        ("Thirty percent confirms the slot. The rest is due after the setup is finished and you've "
         "seen it, by eSewa, Khalti, card or bank transfer. Corporate bookings can be invoiced with "
         "VAT on request.",
         "Thirty percent confirms the slot. The rest is due after the decoration is finished and "
         "you've seen it, by eSewa, Khalti, card or bank transfer. Corporate bookings can be invoiced "
         "with VAT on request."),
    ],
    ("Feature", "title"): [("Real setup photos", "Real decoration photos")],
    ("Feature", "text"): [
        ("Every decorator is background-checked, trained on our setups and rated by customers after "
         "each booking.",
         "Every decorator is background-checked, trained on our products and rated by customers after "
         "each booking."),
        ("If the setup isn't finished by the end of your arrival window, that booking is 25% off, "
         "applied automatically.",
         "If the decoration isn't finished by the end of your arrival window, that booking is 25% off, "
         "applied automatically."),
        ("Book before 2 PM for an evening setup in any metro. Selected packages go out in ninety minutes.",
         "Book before 2 PM for same-evening decoration in any metro. Selected products go out in "
         "ninety minutes."),
    ],
    ("HowItWorksStep", "title"): [("Choose your package", "Choose your product")],
    ("HowItWorksStep", "text"): [
        ("Browse by occasion and pick a setup at a price that's already final. Every listing shows "
         "exactly what arrives with the decorator.",
         "Browse by occasion and pick a product at a price that's already final. Every listing shows "
         "exactly what arrives with the decorator."),
    ],
}


def _rewrite(apps, forwards):
    for (model_name, field), pairs in SEEDED_COPY.items():
        model = apps.get_model("core", model_name)
        for old, new in pairs:
            before, after = (old, new) if forwards else (new, old)
            model.objects.filter(**{field: before}).update(**{field: after})


def forwards(apps, schema_editor):
    _rewrite(apps, forwards=True)


def backwards(apps, schema_editor):
    _rewrite(apps, forwards=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_occasion_event_distinction'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='category',
            name='package_count',
            field=models.PositiveIntegerField(default=0, help_text='The number shown on the card. Leave 0 to show the real count.', verbose_name='Displayed product count'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='core.package', verbose_name='About the product'),
        ),
        migrations.AlterField(
            model_name='event',
            name='package',
            field=models.ForeignKey(blank=True, help_text='The product from the website this event is built around, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.package', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured products fill the homepage grid.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_products_eyebrow',
            field=models.CharField(default='Featured products', help_text='The small line above the heading of the homepage products block.', max_length=60, verbose_name='Homepage eyebrow'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='products_page_title',
            field=models.CharField(default='Every product we offer', max_length=120, verbose_name='Products page heading'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='booked',
            field=models.CharField(blank=True, help_text='The product they had, shown as “Booked …”. Filled in from the linked product.', max_length=140, verbose_name='What they booked'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='package',
            field=models.ForeignKey(blank=True, help_text="Link it to a product and it shows on that product's page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='core.package'),
        ),
    ]
