# Generated by Django 5.2 on 2026-09-14 12:04
"""
The thing a customer books is called a "package" everywhere a person reads it,
matching the model and the /package/<slug>/ address. The public listing moves
from /products/ to /packages/ (the old address redirects).

The data step rewrites seeded copy only where a row still holds the exact text
0015 and 0016 left behind, so anything edited in the panel is left alone.
"""

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

# (model, field): [(old, new), ...]
SEEDED_COPY = {
    ("SiteSettings", "home_products_eyebrow"): [("Featured products", "Featured packages")],
    ("SiteSettings", "home_products_cta_label"): [("See all products", "See all packages")],
    ("SiteSettings", "products_page_title"): [("Every product we offer", "Every package we offer")],
    ("NavLink", "label"): [("Products", "Packages")],
    ("HeroSlide", "description"): [
        ("Pick a product, pick a slot, and a Celebra decorator arrives with everything in the van "
         "— builds it, photographs it, and takes the packaging away.",
         "Pick a package, pick a slot, and a Celebra decorator arrives with everything in the van "
         "— builds it, photographs it, and takes the packaging away."),
    ],
    ("HeroSlide", "meta"): [
        ("148 birthday products \xb7 from Rs. 1,499", "148 birthday packages \xb7 from Rs. 1,499"),
        ("58 wedding products \xb7 from Rs. 7,999", "58 wedding packages \xb7 from Rs. 7,999"),
        ("87 romantic products \xb7 from Rs. 2,199", "87 romantic packages \xb7 from Rs. 2,199"),
        ("112 themed products \xb7 from Rs. 2,999", "112 themed packages \xb7 from Rs. 2,999"),
        ("64 baby shower products \xb7 from Rs. 2,499", "64 baby shower packages \xb7 from Rs. 2,499"),
    ],
    ("HeroSlide", "cta_label"): [("Browse birthday products", "Browse birthday packages")],
    ("FAQ", "answer"): [
        ("Three days is comfortable and gets you the widest choice of slots. Same-day booking is "
         "available in every metro if you order before 2 PM, and a handful of compact products go out "
         "in ninety minutes.",
         "Three days is comfortable and gets you the widest choice of slots. Same-day booking is "
         "available in every metro if you order before 2 PM, and a handful of compact packages go out "
         "in ninety minutes."),
        ("Tell us in the booking notes and the decorator switches to freestanding frames, weighted "
         "bases and removable clips. Most of our products already work this way — we decorate a "
         "lot of rented flats and hotel rooms.",
         "Tell us in the booking notes and the decorator switches to freestanding frames, weighted "
         "bases and removable clips. Most of our packages already work this way — we decorate a "
         "lot of rented flats and hotel rooms."),
    ],
    ("Feature", "text"): [
        ("Every decorator is background-checked, trained on our products and rated by customers after "
         "each booking.",
         "Every decorator is background-checked, trained on our packages and rated by customers after "
         "each booking."),
        ("Book before 2 PM for same-evening decoration in any metro. Selected products go out in "
         "ninety minutes.",
         "Book before 2 PM for same-evening decoration in any metro. Selected packages go out in "
         "ninety minutes."),
    ],
    ("HowItWorksStep", "title"): [("Choose your product", "Choose your package")],
    ("HowItWorksStep", "text"): [
        ("Browse by occasion and pick a product at a price that's already final. Every listing shows "
         "exactly what arrives with the decorator.",
         "Browse by occasion and pick a package at a price that's already final. Every listing shows "
         "exactly what arrives with the decorator."),
    ],
}


def _rewrite(apps, forwards):
    for (model_name, field), pairs in SEEDED_COPY.items():
        model = apps.get_model("core", model_name)
        for old, new in pairs:
            before, after = (old, new) if forwards else (new, old)
            model.objects.filter(**{field: before}).update(**{field: after})


def forwards(apps, schema_editor):
    _rewrite(apps, forwards=True)


def backwards(apps, schema_editor):
    _rewrite(apps, forwards=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_product_wording_hero_and_faq'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='category',
            name='package_count',
            field=models.PositiveIntegerField(default=0, help_text='The number shown on the card. Leave 0 to show the real count.', verbose_name='Displayed package count'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='core.package', verbose_name='About the package'),
        ),
        migrations.AlterField(
            model_name='event',
            name='package',
            field=models.ForeignKey(blank=True, help_text='The package from the website this event is built around, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.package', verbose_name='Package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured packages fill the homepage grid.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_products_cta_label',
            field=models.CharField(blank=True, default='See all packages', help_text='Links to the packages page. Leave blank to hide the button.', max_length=60, verbose_name='Button under the grid'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_products_eyebrow',
            field=models.CharField(default='Featured packages', help_text='The small line above the heading of the homepage packages block.', max_length=60, verbose_name='Homepage eyebrow'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='home_products_limit',
            field=models.PositiveIntegerField(default=8, help_text='The homepage shows this many packages; the rest live on the packages page.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='How many to show at home'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='products_page_eyebrow',
            field=models.CharField(default='The full catalogue', max_length=60, verbose_name='Packages page eyebrow'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='products_page_lead',
            field=models.CharField(blank=True, default='Filter by occasion, budget and rating. Every price is final and includes delivery, setup and clean-up.', max_length=240, verbose_name='Packages page sub-heading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='products_page_title',
            field=models.CharField(default='Every package we offer', max_length=120, verbose_name='Packages page heading'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='products_per_page',
            field=models.PositiveIntegerField(default=9, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(48)], verbose_name='Packages per page'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='booked',
            field=models.CharField(blank=True, help_text='The package they had, shown as “Booked …”. Filled in from the linked package.', max_length=140, verbose_name='What they booked'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='package',
            field=models.ForeignKey(blank=True, help_text="Link it to a package and it shows on that package's page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='core.package'),
        ),
    ]
